### ISSUE TITLE
Start streaming function does not work 

### ISSUE THREAD

**Issue by Hussain-Alsalman** [ProjectTw/TwitteR2Mongo#2]
When I try to run the startStreaming function  I get this message 
`> startStreaming(timeout = 300)`
`[1] "Now starting stream based on the hashtags of the supplied users network"`

> sh: -c: line 0: syntax error near unexpected token `('
> sh: -c: line 0: `Rscript -e library(TwitteR2Mongo);streamingLoop(300,1) &'
> It seems that the commands are not right. 

I am running OS X 10.11.4 and using Rstudio.

**Comment by Bulletninja** [comment]
I have the same problem on OS X 10.11.4 using R 3.3.0, and Rstudio

**Comment by ProjectTw** [comment]
I have no Mac OS for testing but you may try to modify the command which starts a new R instance at lines 76 or 86 depending on the Type of stream you are starting. 

See here: https://github.com/errepeone/TwitteR2Mongo/commit/666da92ea3ce0b0afce764381e0b00f415ff8990 and here: https://github.com/Ashkan33/TwitteR2Mongo/commit/a63a0610ac5195a3c6205d213ad412cc152aedaf
